export default function ExportHtmlReport({ report }) {
  const handleExport = () => {
    if (!report) return;

    const vulns = report.vulnerabilities || [];
    const vulnRows = vulns.map(v => `
      <tr>
        <td><span class="sev sev-${v.severity.toLowerCase()}">${v.severity}</span></td>
        <td>${v.type}</td>
        <td><code>${v.location || 'N/A'}</code></td>
        <td>${v.description || ''}</td>
        <td>${v.recommendation || ''}</td>
      </tr>`).join('');

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Solidify Audit Report</title>
<style>
  body{font-family:system-ui,sans-serif;max-width:1000px;margin:40px auto;padding:20px;color:#333}
  h1{color:#2563eb} .score{font-size:2em;font-weight:700}
  table{width:100%;border-collapse:collapse;margin-top:20px}
  th,td{text-align:left;padding:12px;border-bottom:1px solid #ddd}
  th{background:#f8fafc} .sev{padding:3px 10px;border-radius:4px;font-size:12px;font-weight:700}
  .sev-critical{background:#fef2f2;color:#dc2626}
  .sev-high{background:#fff7ed;color:#ea580c}
  .sev-medium{background:#fefce8;color:#ca8a04}
  .sev-low{background:#f0fdf4;color:#16a34a}
  code{background:#f1f5f9;padding:2px 6px;border-radius:3px;font-size:13px}
</style></head>
<body>
  <h1>Solidify Security Audit Report</h1>
  <p class="score">Score: ${report.score || 'N/A'}/10</p>
  <p>${report.summary || ''}</p>
  <h2>Vulnerabilities (${vulns.length})</h2>
  <table><thead><tr><th>Severity</th><th>Type</th><th>Location</th><th>Description</th><th>Fix</th></tr></thead>
  <tbody>${vulnRows || '<tr><td colspan="5">No vulnerabilities found</td></tr>'}</tbody></table>
  <p style="margin-top:40px;color:#94a3b8;font-size:12px">Generated by Solidify</p>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'audit-' + Date.now() + '.html';
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <button className="secondary-btn" onClick={handleExport} disabled={!report}>HTML</button>
  );
}
